name: four_try
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  appwrite: ^17.0.0
  open_file: ^3.5.10
  path_provider: ^2.1.5
  dio: ^5.4.2
  permission_handler: ^11.0.1
  flutter_file_downloader: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

